import Image from"next/image";import Link from"next/link";import{createClient}from"@/utils/supabase/server";import ProductCard from"./ProductCard";import NewsletterForm from "./NewsletterForm";import type{JournalPost,Product,Quote}from"./types";
export const revalidate=0;
export default async function Home(){const supabase=await createClient();const[{data:productRows},{data:quoteRows},{data:journalRows}]=await Promise.all([supabase.from("products").select("*").order("created_at",{ascending:false}).limit(3),supabase.from("quotes").select("*").order("created_at",{ascending:false}).limit(1),supabase.from("journal").select("*").order("created_at",{ascending:false}).limit(3)]);const products=(productRows||[])as Product[];const quotes=(quoteRows||[])as Quote[];const posts=(journalRows||[])as JournalPost[];const quote=quotes[0]||null;
return <main className="site-shell"><div className="content-wrap">
<section className="hero"><div className="hero-copy"><p className="eyebrow">Beleza real • maturidade luminosa</p><h1 className="display-title">Beleza madura,<br/><em>sem pedir licença.</em></h1><p>Eu criei este espaço para conversar sobre pele, menopausa e autocuidado como a gente conversa entre amigas: com verdade, humor e nenhuma vergonha de brilhar. ✨</p><div className="hero-actions"><Link href="/vitrine" className="luxe-button">Descobrir meus achados →</Link><Link href="/blog" className="ghost-button">Entrar no diário</Link></div></div><div className="hero-portrait"><Image src="/luana.jpg" alt="Luana, fundadora da Entreluar" fill priority sizes="(max-width:760px) 100vw,55vw"/><div className="hero-seal">Entre beleza<br/>e vivência<br/>existe você</div></div></section>
<section className="quote-ribbon glass-panel" aria-label="Pílula do dia"><p className="eyebrow mb-3">Pílula do dia ☾</p><blockquote>“{quote?.quote||"A maturidade não apaga o nosso brilho — ela finalmente ensina onde acender a luz."}”</blockquote><Link href="/pilulas" className="mt-4 inline-flex min-h-11 items-center text-xs font-bold uppercase tracking-[.18em] text-[var(--champagne)]">Mais pílulas →</Link></section>
<section className="section-space"><div className="section-kicker"><span className="eyebrow">Curadoria sem enrolação</span></div><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><h2 className="section-title">Meus últimos<br/><em>achados</em></h2><Link href="/vitrine" className="ghost-button">Ver toda a coleção</Link></div>{products.length?<div className="editorial-grid">{products.map(p=><ProductCard key={p.id} produto={p}/>)}</div>:<div className="empty-state"><span className="mb-3 block text-4xl">◔</span><p className="font-display text-2xl text-[var(--champagne)]">A curadoria está quase pronta.</p><p className="mt-2">Enquanto isso, vem tomar uma dose de inspiração comigo.</p><Link href="/pilulas" className="ghost-button mt-5">Ler pílulas</Link></div>}</section>
<section className="section-space grid gap-8 md:grid-cols-[.8fr_1.2fr] md:items-center"><div className="relative min-h-[420px] overflow-hidden rounded-[32px_32px_120px_32px] border border-[var(--line)]"><Image src="/luana.jpg" alt="Luana em seu espaço" fill sizes="(max-width:760px) 100vw,40vw" className="object-cover object-[center_35%]"/></div><div><p className="eyebrow">Prazer, eu sou a Luana</p><h2 className="section-title mt-4">Mais vida.<br/>Menos regras.</h2><p className="muted my-6 max-w-xl text-base leading-8">Aqui eu testo, estudo, erro, acerto e divido tudo sem filtro. Porque a mulher que eu me tornei não quer parecer mais nova — quer se sentir cada vez mais viva.</p><Link href="/sobre" className="luxe-button">Conhecer nossa história →</Link></div></section>
<section className="section-space"><div className="section-kicker"><span className="eyebrow">Conversas que ficam</span></div><h2 className="section-title mb-8">Do meu diário<br/>para o seu</h2>{posts.length?<div className="editorial-grid">{posts.map(p=><Link key={p.id} href={p.category==="Estudei para te explicar"?`/resenhas/${p.id}`:`/blog/${p.id}`} className="luxe-card group block"><div className="relative aspect-[4/3]">{p.image_url?<Image src={p.image_url} alt="" fill sizes="(max-width:760px) 100vw,33vw" className="object-cover transition duration-700 group-hover:scale-105" unoptimized/>:<div className="h-full bg-gradient-to-br from-[#76283b] to-[#16070b]"/>}</div><div className="p-6"><p className="eyebrow">{p.category||"Diário"}</p><h3 className="font-display mt-3 text-3xl leading-none">{p.title}</h3><span className="mt-5 inline-flex text-xs font-bold uppercase tracking-[.16em] text-[var(--champagne)]">Ler com calma →</span></div></Link>)}</div>:<div className="empty-state">Novas conversas estão sendo preparadas. Volte para a nossa próxima confidência. 🤫</div>}</section>
<section className="section-space"><div className="glass-panel rounded-[34px] px-6 py-12 text-center md:px-14"><p className="eyebrow">Clube da Luana</p><h2 className="section-title my-5">Cartas para<br/>amigas.</h2><p className="muted mx-auto mb-7 max-w-xl leading-7">Deixe seu e-mail para receber meus achadinhos, novos desabafos e fofocas direto na sua caixa de entrada. Sem spam, só conversa boa.</p><NewsletterForm /></div></section>
<section className="glass-panel section-space rounded-[34px] px-6 py-12 text-center md:px-14"><p className="eyebrow">Nos encontramos também por lá</p><h2 className="section-title my-5">Um pouco de brilho<br/>no seu feed.</h2><p className="muted mx-auto mb-7 max-w-xl leading-7">Bastidores, achados rápidos e aquela conversa que começa com “amiga, preciso te contar”.</p><a href="https://instagram.com/entreluarBeauty" target="_blank" rel="noreferrer" className="luxe-button">@entreluarBeauty ↗</a></section>
</div></main>}
